Dev
Taiwrash/dev-resume pull request #6
Opened 2020-09-30 15:31 UTC by PerezArturo

Add new dev

2020-09-30 16:08 UTC, Taiwrash requested changes
Great work @PerezArturo , you did a great job but there's an extra curly bracket at the end which you forgot to remove. Please remove it and your PR will get merged in no time

2020-10-01 03:26 UTC, PerezArturo commented
The change are done

2020-10-01 06:02 UTC, Taiwrash approved these changes

2020-10-01 06:04 UTC, Taiwrash commented
@all-contributors please add @PerezArturo  for infrastructure, tests and code

2020-10-01 06:04 UTC, merged